# Generated by Django 5.1.6 on 2025-05-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total_seats',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
